### ISSUE TITLE
Traceback running deploy.py

### ISSUE THREAD

**Issue by amulheirn** [tendenci/tendenci#539]
I've been following the installation process here:  https://tendenci.readthedocs.io/en/latest/installation/installation.html#system-requirements

My installation is on an AWS host running Ubuntu 16.04.1 LTS.   

All goes very well, until I come to run the deploy.py part, when I get the following:

``(venv) ubuntu@ip-172-31-40-149:/var/www/t289rmembers$ sudo python deploy.py
Operations to perform:
  Synchronize unmigrated apps: django_admin_bootstrapped, tendenci, accounts, formtools, bootstrap3, gis, api_tasty, tinymce, djkombu, theme, humanize, haystack, model_report, gunicorn, tags, staticfiles, sitemaps, registry, pagination, mobile, admindocs, messages, social_media, styled_forms
  Apply all migrations: staff, accountings, redirects, videos, invoices, imports, locations, email_blocks, captcha, navs, meta, explorer_extensions, registration, stories, case_studies, user_groups, contributions, payments, industries, regions, speakers, entities, contacts, event_logs, forums, tastypie, sites, corporate_memberships, pages, forms, discounts, contenttypes, wp_importer, tagging, site_settings, theme_editor, ics, announcements, social_services, events, careers, make_payments, files, studygroups, exports, newsletters, jobs, explorer, sessions, robots, auth, educations, metrics, notifications, boxes, base, campaign_monitor, tendenci_guide, news, emails, categories, articles, search, committees, handler404, photos, admin, perms, directories, versions, djcelery, social_auth, profiles, recurring_payments, memberships, reports, testimonials, donations, dashboard, resumes, help_files, wp_exporter
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "deploy.py", line 3, in <module>
    subprocess.check_call(['python', 'manage.py',  'migrate', '--noinput'])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'migrate', '--noinput']' returned non-zero exit status -9``

Not quite sure what is causing that.  I did all this work this evening (12th December) so it should be the latest from the repo.

Hope someone can advise or point me in the right direction...

Thanks, Andrew

**Comment by eschipul** [comment]
Andrew - I'm betting it is a missed migration on our part. Rather than ask for every log trace, I would like to confirm you are doing a fresh install on Ubuntu server 16.04 LTS and have already run "sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade" as baseline. 

I need to do a fresh install from the latest iso later this week either way. Sorry for the trouble. Feel free to confirm versions etc, but hopefully I will be able to recreate it.

**Comment by amulheirn** [comment]
Thanks for responding so quickly Ed.

The server is indeed 16.04.1 LTS and is relatively new, but not 100% new.  I had already installed another product using Apache and Mysql on there, but hopefully that isn't an issue - the other product doesn't use Django or Python.     I could see if I can wipe the server and start again if you want me to confirm.

One thing I forgot to mention - the Curl script for generating the 32 character keys did not work for me.  So I made my own keys up in local_settings.py and made sure they were 32 characters in length.  Hopefully that is not a part of the issue?

Another thing I did differently to the docs is the postgresql-contrib package wouldn't install with a version number at the end, nor would postgis.

Yes - I did do those commands you mentioned.  Here's the 'history' output from what I did in case it helps.

``
  119  sudo apt-get update
  120  sudo apt-get dist-upgrade
  121  sudo apt-get install build-essential python-dev libevent-dev libpq-dev libjpeg8 libjpeg-dev libfreetype6 libfreetype6-dev
  122  sudo apt-get install git
  123  sudo apt-get install unattended-upgrades update-notifier-common
  124  sudo dpkg-reconfigure -plow unattended-upgrades
  125  sudo apt-get install python-pip
  126  sudo pip install virtualenv
  127  sudo apt-get install postgresql postgresql-contrib-9.3 postgresql-9.3-postgis-2.1
  128  sudo apt-get install postgresql postgresql-contrib
  129  sudo apt-get install postgresql-9.3-postgis
  130  sudo apt-get install postgresql-postgis
  131  sudo apt-get install postgis
  132  DB_USER=<USERNAME REMOVED>
  133  DB_PASS=<PASSWORD REMOVED>
  134  DB_NAME=<DB NAME REMOVED>
  135  sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';"
  136  sudo -u postgres psql -c "CREATE DATABASE $DB_NAME WITH OWNER $DB_USER;"
  137  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
  138  sudo -u postgres psql -d $DB_NAME -c "CREATE EXTENSION postgis;"
  139  sudo -u postgres psql -d $DB_NAME -c "CREATE EXTENSION postgis_topology;"
  140  sudo -u postgres psql -d $DB_NAME -c "CREATE EXTENSION fuzzystrmatch;"
  141  sudo -u postgres psql -d $DB_NAME -c "CREATE EXTENSION postgis_tiger_geocoder;"
  142  sudo mkdir /srv/tendenci/ cd /srv/tendenci/
  143  ls /srv
  144  cd /srv/tendenci/
  145  ls
  146  sudo virtualenv venv source venv/bin/activate
  147  sudo virtualenv venv
  148  source venv/bin/activate
  149  sudo pip install "Django>=1.8,<1.9"
  150  cd /var/www
  151  sudo django-admin.py startproject --template=https://github.com/tendenci/tendenci-project-template/archive/master.zip t289rmembers
  152  ls
  153  cd t289rmembers/
  154  sudo pip install -r requirements/dev.txt
  155  ls
  156  cd conf
  157  ls
  158  sudo vim settings.py
  159  sudo vim local_settings.py
  160  curl https://gist.githubusercontent.com/jennyq/45de71a93cff774c593d/raw/30ede14eb133de66cc839cc0458a1e915368534e/setup_keys.sh | bash
  161  cd ..
  162  curl https://gist.githubusercontent.com/jennyq/45de71a93cff774c593d/raw/30ede14eb133de66cc839cc0458a1e915368534e/setup_keys.sh | bash
  163  sudo curl https://gist.githubusercontent.com/jennyq/45de71a93cff774c593d/raw/30ede14eb133de66cc839cc0458a1e915368534e/setup_keys.sh | bash
  164  sudo vim conf/local_settings.py
  165  ls
  166  bash migrate_initials.sh
  167  sudo bash migrate_initials.sh
  168  python deploy.py
  169  sudo python deploy.py
  170  ls
  171  sudo python deploy.py
  172  more deploy.py
  173  django -v
  174  cd conf/
  175  vim local_settings.py
  176  sudo vim local_settings.py
  177  cd ..
  178  more deploy.py
  179  sudo python deploy.py
  180  exit
``

**Comment by eschipul** [comment]
I haven't forgotten this. My VM test install on 16.04 LTS did force me to make numerous changes to support GIS (required for Tendenci) so I had to install Postgres 9.5 with the 2.2 GIS extensions. Before I update the docs, I need to finish a traditional install and test if the migrations work on the newer version of Postgres.

What would be helpful is for you to let me know 
1) which version of Postgresql you have installed on Xenial? 
2) did you encounter any errors installing the GIS extensions? Or, given this part isn't documented currently (I'll fix once I know) did you do an "apt-get distribution-upgrade" to go from 14.04 to 16.04? (I know you said it was a fresh install, just double checking.)

I'll keep following up even if you don't get a chance to reply. I do think it is very important to make it easier for everyone to install. That is my fault and I'm working on it and I truly appreciate your help!

Thanks - Ed

**Comment by jennyq** [comment]
The error occurred on migration trying to update the `dashboard` stats before migrating `event_logs`. The latest Django 1.8.x doesn't seem to respect the order of `INSTALLED_APPS` on migration because the installation tested for the same version of `tendenci` (7.2.48) worked fine on Nov. 27. Anyway, we have pushed out a fix to make sure `event_logs` get migrated before `dashboard`.

Please try again. My test was conducted only on Ubuntu 14.04 LTS in a VMware instance . I haven't tested on Ubuntu 16.04 LTS yet.

**Comment by mhvis** [comment]
I'm having this exact issue now almost a year later. It has come up when I carefully followed the installation guide, on a Google Cloud Compute Engine virtual machine instance with Ubuntu 16.04 LTS and Ubuntu 14.04 LTS (tried it twice). `tendenci` version is 7.4.0, `Django` 1.8.18, `python` 2.7.6.

**Comment by PaulSD** [comment]
Google Could VMs apparently have a global `/etc/boto.cfg` that tends to wreak havoc.

Try adding `BOTO_CONFIG=/bogus/value` to your local_settings.py.

See:
https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
https://github.com/boto/boto/issues/3263
https://github.com/boto/boto/issues/3717
https://github.com/GoogleCloudPlatform/compute-image-packages/issues/262
https://stackoverflow.com/questions/40732313/gensim-installation-problems

**Comment by mhvis** [comment]
Hi, a huge thanks for your fast and very helpful response :)! That clears up the issue for me, hadn't yet discovered that it had to do with the Google Cloud VM. Adding the `BOTO_CONFIG` value didn't fix it, but the solution on StackOverflow worked (`pip install google-compute-engine`). Thanks again!

**Comment by eschipul** [comment]
I learn something from @PaulSD and @jennyq every single day. Glad that worked - it was new knowledge to me as well.
