### ISSUE TITLE
Group memberships

### ISSUE THREAD

**Issue by AdamBark** [tendenci/tendenci#812]
I'm trying to set up a family membership i.e. one member pays for a family membership and that can cover several members. It seems like it is a generalisation of the corporate membership. Is there a way to do this now without tangling up families or other groups with corporations?

If this isn't currently possible where do you suggest it is added? In a separate module or by generalising the current corporate membership module?

**Comment by eschipul** [comment]
@AdamBark I agree this is a needed feature. However, family memberships is a very very complicated issue. Just ask any PTA President who has tried to put out a directory of students at the local high school. It is a multi-variable EAV problem with children who can be associated with sometimes up to three families (or more). 

Salesforce tackles it by making everyone (like EVERYONE) part of one organization, or with an org for each family. Neither scales or allows tracking.

No doubt, this is needed to track familial donations or recurring donations. It's just wildly complex. 

In the short term, consider a membership with a limited number of discount codes for other memberships (presumably within the family.) 

If you have the time, perhaps discuss this with people you know IRL and ask about their family structures. The TV show "Modern Family" is actually pretty accurate, so it becomes a challenge to be inclusive while extending monetary benefits (event pricing, job listings, etc...). I'm open to suggestions and certainly 100% for being inclusive, just at a loss for how to actually implement it without either excluding people unfairly, or allowing people to cheat the system.

Lastly, Yes, it is a valid and good question. In fact most organizations that do NOT charge for memberships fail long-term in my observation.  What I don't want is to have familial relationships "designated" in the software as that seems over the line to me. (I like my privacy.)

**Comment by AdamBark** [comment]
My use case is quite a small organisation (less than 100 members currently) so I only really want to offer this membership to specific people that we discuss it with. Of course this doesn't help for a generalisation! My point is it's more like a household rather than a family and I don't need to group people other than for payment and so we can have all members registered as such not just the payee.

Is it possible to automatically create discount codes? We have only monthly memberships and I use recurring payments so it would add some administrative burden otherwise.

I suppose all I need is a way to have a generic group membership and I can approve them myself.

**Comment by eschipul** [comment]
@AdamBark That simplifies it quite a bit, although knowing how people use the software my bet is they expand the functional requirements. But let's start simple. If you manually set up the user, or allow self registration (in settings) then Tendenci will handle the recurring via: (example link, no real data, but you get the point) - https://demo.tendenci.com/rp/customers/

We do recommend stripe.com because they are talking to the community about (hopefully!?) giving a better discount for NPOs/NGOs if the group numbers reach a certain level. I'm not good at the negotiation thing, so who knows, but I do know they are way cheaper than auth+firstdata or paypal.

In theory, a custom membership application associated with a corporate membership, with the individual membership subject to approval (kinda normal with professional orgs anyway), would do the trick.

Do you mind giving that a try and letting us know if that works? 

There are some awesome devs that also monitor the issues on here like @PaulSD and @goetzk and of course @jennyq (she ROCKS!!!) who may also have some input on best practices. We are (quite seriously) a tiny virtual company behind an international community. I try to do my best, and I do know that the software is awesome when configured properly. - Ed

**Comment by jennyq** [comment]
Hi @AdamBark, you can simply set up a corporate membership application with the price of 0 for the associated individual membership type (ex: https://demo.tendenci.com/admin/memberships/membershiptype/3/change/). And if you want to approve them yourself, set the "Authentication Method" to "Admin Approval" https://demo.tendenci.com/admin/corporate_memberships/corpmembershipapp/1/change/.

**Comment by AdamBark** [comment]
Thanks Ed and Jenny. I understand how to use the corporate membership I was just hoping to have a different application but it seems that the corporate membership module only allows for one application to be active. Also the corporation selection page https://demo.tendenci.com/memberships/applications/corp-pre-add/ is fixed so you can't have different lists for different categories.

**Comment by jennyq** [comment]
Yes, one application for corporate memberships. But you can set up multiple corporate membership types. Would that still not work?

**Comment by AdamBark** [comment]
It's fine I suppose just, like I said, there's no way to split up different kinds of groups; all your corporations, families, other organisations have to go into one bucket.

**Comment by jennyq** [comment]
You're right on one link for joining corporate memberships. But when you have multiple membership types, it will automatically create a group for each membership type. What you can do is to create a separate page to list all the categories (membership types) and benefits.

**Comment by AdamBark** [comment]
Would you accept pull requests to generalise the language in that module?

**Comment by AdamBark** [comment]
There's no auto-renewal option for corporate memberships?

**Comment by jennyq** [comment]
> Would you accept pull requests to generalise the language in that module?

Pull requests are always welcome. Would you mind talking it a bit what exactly you're going to change?

> There's no auto-renewal option for corporate memberships?

Right, the auto-renewal option exists in memberships only.

**Comment by goetzk** [comment]
Hi @AdamBark , @eschipul and others.

Here comes a horrible work around from Mr Horrid Hacks (my codebases must be like a haunted horror house to Ed!)

I'm aware this doesn't solve the problem in a general case, but thought I'd offer a work around which doesn't require the corporate membership and allows auto renew to work (with provisos) and I think soves the 80% case.

Two admin only / hidden memberships
- "family admin", $x renewal, auto renew capable
- "family member", $0 renewal, no auto renew

Make a private group for the family (Ideally automatic on 'admin membership' creation via signals)
- one person to be invoiced moved to family admin membership
- all other family members moved to 'family member' membership
- people could be in multiple families (groups) in this scheme.

So the flow is admin membership funded -> group auto created -> members manually added (ideally by the family admin through good use of tendenci permissions but manually by a site admin if needed).

Using groups is good because it lets you lean on existing groups support like https://www.tendenci.com/help-files/topic/49/ .

When admin is renewed, a scheduled job (or better a registered signal) renews all other "family member" level members in that admins group.

Key Outstanding issue: People who appear in multiple families. They either need a membership per family (ugly) or are always valid members as long as one of their family groups is still valid (less ugly). If using the second option the new membership should probably be set to the same expiry as the 'family admin' which renewed it.

i haven't mapped out all the ways a family can be 'broken up' (redistributed?) but something like the above should be workable for most cases.

I don't expect the above would require a lot of actual code (less than 100 lines is my guess) but it would need extensive testing so would probably be a project of several days just to find out if it will work as I'm imagining it will.

Thanks,
Karl.

**Comment by eschipul** [comment]
@goetzk Oh you are killing me man.... (the best part is you know it and are poking fun at me, which I find very funny in a good natured way. Ya, ya, I'm particular about data structures. #heh 

Anyway, families - I've fought this battle and failed in the past. I do truly get the request, I want it as well. Nothing is more annoying that when a non-profit I support calls me for a donation a week after my wife JUST made a donation! It's frustrating.

I just keep going back to the "PTA student directory" example. While compiling it we found.

1) Kids who were associated with multiple families (divorces, remarriages, etc)
2) Kids associated with one or two families, but whose names did not match EITHER parents names.
3) Extreme security concerns with who could update the students records.
4) Parents, or guardians, or grandparents, who did not notify the school when a domestic dispute caused a change in who could pick up the child. (Human issue, files were updated but easier for PTA Mom's and Dad's to just look at the convenient student index.)
5) People not understanding that one family might have children of different races and causing a scene because they could grasp it and might block a parent from going on a field trip as guardian.
6) Older siblings - my family has a large age gap between the first three and the rest. So I was an approved "guardian" and could make decisions for the younger ones, but I was not their parent and the system didn't handle guardianship. (in the school scenario, which was real, it worked because they knew us, but it was a small school.)

So you are looking at a seriously complex many-to-many-to-many set of relationships involving generations, names, divorces, responsibilities, restraining orders, approved guardians outside of the family and more.

I do believe it IS possible. But it would probably need to be an identity based solution using API calls. Families are sacred. And they truly look like that TV show "Modern Family." It's definitely not a small task, and the stakes are very high as none of us know how someone is going to implement the software in China. There are no back doors, or "phone home" features because I'm really into privacy and have no desire to enable a dystopian future of complete control, not necessarily by the govt, but it could also occur via Facebook!

This is giving me a headache. Any viable solutions?

**Comment by AdamBark** [comment]
I kind of wish I hadn't mentioned 'family' now. What's the best way to have one user pay for several memberships upfront? It sounds like @goetzk's suggestion should work for me.

**Comment by eschipul** [comment]
Thoughts on the simplified explanation @AdamBark 

1) Use Organizational Memberships, maybe with modifications.

2) New module that supported "Membership Credits" that could be redeemed with a discount code similar to a ballot. This gets into a near "banking" territory which comes with it's own issues (in state/out of state / taxable/ etc)

3) OR, my suggestion, enable the "pay by check" option on the form and just have them prepay and reconcile it. Unless you are talking 10,000 k plus people, this would be a low cost way to start using it today. I always like to beta test before committing resources so this makes the most sense to me.

Workflow on 3 is they sign up, it sits in unpaid status, a human approves it based on if it was prepaid. That would work immediately and tell you what the customers actually want at little to no cost.
